// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loyalty_application.Data;

#nullable disable

namespace loyalty_application.Migrations
{
    [DbContext(typeof(RewardsDbContext))]
    [Migration("20260520032636_AddTransactionsAndPointLedger")]
    partial class AddTransactionsAndPointLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("loyalty_application.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("loyalty_application.Models.PointLedgerEntry", b =>
                {
                    b.Property<int>("PointLedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsChanged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PurchaseTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PointLedgerEntryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PurchaseTransactionId");

                    b.ToTable("PointLedgerEntries");
                });

            modelBuilder.Entity("loyalty_application.Models.PurchaseTransaction", b =>
                {
                    b.Property<int>("PurchaseTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasePointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusPointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseTransactionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseTransactions");
                });

            modelBuilder.Entity("loyalty_application.Models.PointLedgerEntry", b =>
                {
                    b.HasOne("loyalty_application.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("loyalty_application.Models.PurchaseTransaction", "PurchaseTransaction")
                        .WithMany()
                        .HasForeignKey("PurchaseTransactionId");

                    b.Navigation("Customer");

                    b.Navigation("PurchaseTransaction");
                });

            modelBuilder.Entity("loyalty_application.Models.PurchaseTransaction", b =>
                {
                    b.HasOne("loyalty_application.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
